os: osx
language: c
install: 
    - brew update
    - brew install python3
    - brew install scons

compiler:
  - clang
  - gcc
script: 
    - scons VERBOSE=1 
    - scons config
    - export RM_TS_PRINT_CMD=1
    - export RM_TS_PEDANTIC=0
    - sudo -E nosetests3 -s -v -a '!slow'
